# .streamlit/secrets.toml

[connections.supabase]
url = "https://oktgbkyttyjgnhzydnzf.supabase.co"
key = "sb_publishable_TjYuKH-AAOSvoAIBq09jTw_JmIc7kne"

[connections.gemini]
api_key = "AIzaSyCPiuB2gw3gxzRnUYprY6v6_21nKmR_RpM"

[features]
require_auth = false

[oauth]
app_url = "http://localhost:8501"
